FROM resin/armv7hf-debian:jessie
LABEL io.resin.device-type="beaglebone-green-wifi"
COPY . /hello
WORKDIR /hello
RUN arm-linux-gnueabihf-gcc -o hello hello.c

# Enable systemd init system in container
ENV INITSYSTEM on

CMD ["./hello"]
