FROM resin/armv7hf-debian:jessie
LABEL io.resin.device-type="beaglebone-green-wifi"

RUN apt-get update && apt-get install -y build-essential

COPY . /hello
WORKDIR /hello
RUN gcc -o hello hello.c

# Enable systemd init system in container
ENV INITSYSTEM on

CMD ["./hello"]
